on:
  push:
    branches:
      - test
    
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - run: node test.js
        env: 
          GH_TOKEN: ${{ github.token }}
          REPOSITORY_ID: ${{ github.repository_id }}